questionsコントローラー（記事一覧取得）の作成
project-rqb/project-rqb-back pull request #43
Opened 2024-07-18 09:01 UTC by gorilla-muscle

## issue
#18 
<br>

## 概要
質問記事一覧を取得するためのquestionsコントローラーを作成しました。
また、質問記事一覧のJsonデータを整形するために`Active_Model_Serializers`を導入しました。
<br>

## 変更内容
- `app/api/v1`配下に`questions_controller.rb`を作成
- `app/serializers`配下に`question_serializer.rb`・`user_serializer.rb`を作成
- `config/application.rb`内に`active_model_serializers`をオートロードするための記述を追加
- `config/routes.rb`内にルーティングを追加
- `db/seeds`配下に開発環境用のseedsファイル`development.rb`を追加
<br>

## 確認手順
- [ ] **Questionsコントローラーの作成・アクションの定義**
  - [ ] Questionsコントローラーが正しく作成されているか。
  - [ ] `index`アクション内にてQuestionモデルの全レコードが取得できるようになっているか。
  - [ ] Questionモデルに紐づくUserモデルを取得するために、N+1問題を解決出来ているか。
  - [ ] `QuestionSerializer`を使用し、正しいJSONデータを送信できているか。
- [ ] **Serializerの設定**
  - [ ] `QuestionSerializer`が正しく作成されているか。
  - [ ] `UserSerializer`が正しく作成されているか。
  - [ ] `QuestionSerializer`・`UserSerializer`のアソシエーションが定義されているか。
- [ ] **ルーティングの設定**
  - [ ] `config/routes.rb`内に、Questionsコントローラーに対するルーティングが正しく設定されているか。
- [ ] **seedデータの作成**
  - [ ] User・Questionモデルに関するseedデータが問題なく作成できるか。
- [ ] **動作確認**
  - [ ] ブラウザまたはPostmanにて『 http://localhost:3000/api/v1/questions 』アクセス時、下記《動作画面》の通りにJSONデータが送信されているか。
<br>

## 動作画面
### ブラウザの場合
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/d45f7e9d-65cc-4b69-8e37-8a5f20a6db85">
<br>

### Postmanの場合
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/a42a1a75-8406-4dd7-98ec-e7911ed2325f">

2024-07-18 09:10 UTC, topi0247 reviewed
ご対応ありがとうございます！
２点よろしくお願いします

１．一覧ページからユーザーページに飛ぶことも可能にしているので、userのuuidも一緒に送っていただけると嬉しいです
２．https://github.com/project-rqb/project-rqb-back/pull/33 がまだマージされていないので、こちらマージ後に改めて作業ブランチに反映していただきコンフリクト対応を行っていただければと思います

今回一覧のみの取得なので、下記対応は別issueと判断してレビューしております。
認識間違いないか確認していただければと思います
- ページネーション
- ソート（新着順・古い順）
- 質問のタグ

2024-07-18 09:19 UTC, gorilla-muscle commented
> ご対応ありがとうございます！ ２点よろしくお願いします
> 
> １．一覧ページからユーザーページに飛ぶことも可能にしているので、userのuuidも一緒に送っていただけると嬉しいです ２．#33 がまだマージされていないので、こちらマージ後に改めて作業ブランチに反映していただきコンフリクト対応を行っていただければと思います
> 
> 今回一覧のみの取得なので、下記対応は別issueと判断してレビューしております。 認識間違いないか確認していただければと思います
> 
> * ページネーション
> * ソート（新着順・古い順）
> * 質問のタグ

１.２ について了解しました！
また、今回は『**記事一覧の取得**』に関する実装なので、上記対応については別issueでの実装という認識で問題ありません。
よろしくお願いいたします。

2024-07-18 09:34 UTC, UNNNYOU approved these changes
特段変なところは見当たりませんでした！！
LGTMです！！

2024-07-19 06:37 UTC, topi0247 commented
userのuuidはカラム無いので一旦uidの方送っていただければと思います！
すみませんがよろしくお願いします！

2024-07-19 15:32 UTC, gorilla-muscle commented
お疲れ様です！
以下の内容について修正を行いましたので、確認をお願いします。
<br>

## 修正内容
- `app/serializers/user_serializer.rb`にて、JSONデータにUserモデルのuidを含むように追記。
- #33 merge後のmainブランチとのコンフリクトを解消。
  - `config/routes.rb`のquestionsルーティングの設定においてコンフリクトが発生、両ブランチの変更を取り込むことで解消。
<br>

## 動作画面
![image](https://github.com/user-attachments/assets/aa38528d-1f06-4fcc-b423-9a2739063f6d)

2024-07-20 00:37 UTC, UNNNYOU commented
確認行いました！！
再度にはなりますが、LGTMです！！

2024-07-20 06:28 UTC, topi0247 commented
ご対応ありがとうございます！
https://github.com/project-rqb/project-rqb-back/pull/44
こちらでuuidがuserに導入されるので、そちらマージされたらuid⇨uuidにしていただけると助かります
何度もすみません！よろしくお願いします！！

2024-07-20 09:09 UTC, UNNNYOU commented
serializerはrecoilに追加するものを僕の方で追加しようと思っているので、最悪そのままにしていただいて大丈夫っすよ！

2024-07-20 15:14 UTC, topi0247 commented
> serializerはrecoilに追加するものを僕の方で追加しようと思っているので、最悪そのままにしていただいて大丈夫っすよ！


了解です！

2024-07-20 15:15 UTC, topi0247 approved these changes
userのuuidは @UNNNYOU さんの方で行うということで把握しました！
LGTMです！ごたいおうありがとうございました！

2024-07-21 13:29 UTC, topi0247 requested changes

2024-07-21 13:29 UTC, topi0247 commented on app/controllers/api/v1/questions_controller.rb
> +class Api::V1::QuestionsController < ApplicationController
`ApplicationController`の継承を`Api::V1::BasesController`の方にしていただけると嬉しいです！

2024-07-26 04:45 UTC, gorilla-muscle commented
お疲れ様です！

遅くなってしまいましたが、以下《修正内容》の通りに修正を行いました！
確認の方、よろしくお願いします。
<br>

## 修正内容
- `app/contorllers/api/v1/qustions_controller.rb`にて、クラスの継承元を`ApplicationController`から`Api::V1::BasesController`に修正。

2024-07-26 07:30 UTC, UNNNYOU approved these changes
ご連絡遅くなりすみません！
ご対応ありがとうございます！！
LGTMです！！

2024-07-26 13:20 UTC, topi0247 approved these changes
ご対応ありがとうございました！LGTMです！

2024-07-26 14:36 UTC, merged